// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdOcdwYab8hav6Q1tNlanX_L5INswWwbE',
    appId: '1:21917572685:web:4bf2aa2ec1da6c57154604',
    messagingSenderId: '21917572685',
    projectId: 'plxntask-759a1',
    authDomain: 'plxntask-759a1.firebaseapp.com',
    databaseURL: 'https://plxntask-759a1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'plxntask-759a1.appspot.com',
    measurementId: 'G-C5FE3FP7JF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmZfF_S6cPY3_Qq0hIRM6bL6kM_-kdPzE',
    appId: '1:21917572685:android:27a83e6b7ddf9d52154604',
    messagingSenderId: '21917572685',
    projectId: 'plxntask-759a1',
    databaseURL: 'https://plxntask-759a1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'plxntask-759a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVGqNsb8PPeoEwSJGMuZcrWav6CcoQJlY',
    appId: '1:21917572685:ios:732a8be60c03bbbf154604',
    messagingSenderId: '21917572685',
    projectId: 'plxntask-759a1',
    databaseURL: 'https://plxntask-759a1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'plxntask-759a1.appspot.com',
    androidClientId: '21917572685-6rua0p8s27k3hjepadkgk004mtd8b9rd.apps.googleusercontent.com',
    iosClientId: '21917572685-kj49og48hm1pd21ehgnhl3gvasgmhtu3.apps.googleusercontent.com',
    iosBundleId: 'com.example.plxntask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVGqNsb8PPeoEwSJGMuZcrWav6CcoQJlY',
    appId: '1:21917572685:ios:732a8be60c03bbbf154604',
    messagingSenderId: '21917572685',
    projectId: 'plxntask-759a1',
    databaseURL: 'https://plxntask-759a1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'plxntask-759a1.appspot.com',
    androidClientId: '21917572685-6rua0p8s27k3hjepadkgk004mtd8b9rd.apps.googleusercontent.com',
    iosClientId: '21917572685-kj49og48hm1pd21ehgnhl3gvasgmhtu3.apps.googleusercontent.com',
    iosBundleId: 'com.example.plxntask',
  );
}
